# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f5814f35153322401dbab0c59086402be2a0616983c3eae9c3c7ec80773568fa3fb68a93d8e58a243205f1b6d1d2c0eb039291eabdf237ad798ae074802f8e48

test:
  secret_key_base: 72dc6b367bf99beccb2dc3581ebd3654e0db887482d8bc1921feda1ec48ef771ea9fbec3a48490376a1f19efb6a9c03f3cda8d7b161d846739cfd917d186afe2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
